[app]
app_server ansible_host=98.81.103.180

[db]
db_server ansible_host=10.0.2.53

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/quickbite-key.pem
ansible_python_interpreter=/usr/bin/python3

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/quickbite-key.pem -o StrictHostKeyChecking=no ubuntu@98.81.103.180"'
